[project]
name = "aiosvkmimer"
#version = "0.0.1" # DO NOT CHANGE
authors = [
    { name="Robin Ostlund", email="me@robinostlund.name" }
]
description = "Asyncio library for SVK Mimer"
readme = "README.md"
requires-python = ">3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies", "version"]

[project.urls]
"Homepage" = "https://github.com/robinostlund/aiosvkmimer"
"Bug Tracker" = "https://github.com/robinostlund/aiosvkmimer/issues"

[build-system]
requires = [
    "setuptools>=65",
    "wheel>=0.37.0",
    "setuptools_scm[toml]>=6.2"
]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
where = ["aiosvkmimer"]
exclude = [".github*", "tests*"]

[tool.setuptools_scm]
fallback_version = "0.0.1"
write_to = "aiosvkmimer/version.py"

[tool.black]
line-length = 120
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'
extend-exclude = '''
/(
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
)/
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
asyncio_mode = "strict"
testpaths = ["tests"]
python_files = ["test_*.py"]