# name: "CodeCov"
# on: [push]
# jobs:
#   analyze:
#     name: Analyze
#     runs-on: ubuntu-latest
#     env:
#       OS: ubuntu-latest
#       PYTHON: '3.9'

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.9

#       - name: Generate coverage report
#         run: |
#           pip install -r requirements-test.txt
#           pytest --cov=./ --cov-report=xml

#       # documentation: https://github.com/codecov/codecov-action
#       - name: Upload Coverage to Codecov
#         uses: codecov/codecov-action@v3
#         with:
#           directory: ./coverage/reports/
#           env_vars: OS,PYTHON
#           fail_ci_if_error: true
#           files: ./coverage.xml
#           flags: unittests
#           name: codecov-aiosvkmimer
#           verbose: true
