name: Publish

on:
  release:
    types: [released]

jobs:
  pypi-publish:
    if: "!github.event.release.prerelease"
    name: Upload Package to PyPi Repository
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/aiosvkmimer
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel twine setuptools setuptools_scm
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # - name: Extract tag name
      #   id: tag
      #   run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3)
      #   run: echo "{TAG_NAME}=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT

      # - name: Get the release version
      #   id: get_version
      #   run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

      # - name: Update version in pyproject.toml
      #   run: >-
      #     sed -i "s/version = \"0.0.1\"/version = \"${{ steps.get_version.outputs.VERSION }}\"/g" pyproject.toml

      # - name: Update version in pyproject.toml
      #   run: >-
      #     sed -i "s/{{VERSION_PLACEHOLDER}}/${{ GITHUB_REF }}/g" pyproject.toml

      - name: Build package
        run: |
          python -m build --outdir dist/
          python -m twine check dist/*
          python -m setuptools_scm --strip-dev

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN_PROD }}
          packages-dir: dist/
          print-hash: true
          verbose: true

      # - name: Publish package to PyPI
      #   if: startsWith(github.ref, 'refs/tags')
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     password: ${{ secrets.PYPI_TOKEN_PROD }}
