name: Publish

on:
  release:
    types: [released]

jobs:
  pypi-publish:
    if: "!github.event.release.prerelease"
    name: Upload Package to PyPi Repository
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/aiosvkmimer
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel twine setuptools setuptools_scm
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build package
        run: |
          python -m build --outdir dist/
          python -m twine check dist/*
          python -m setuptools_scm --strip-dev

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN_PROD }}
          packages-dir: dist/
          print-hash: true

